---
name: 2. Single Email Request
description: Single Email template
body:
- type: textarea
  attributes:
    label: Proposed Audience
    placeholder: "Audience selection criteria, list etc"
  validations:
    required: true
- type: input
  id: dates
  attributes:
    label: Test and Send Dates
    description: Provide Test and Send date
    placeholder: ex. 06/01/2021
  validations:
    required: true
- type: input
  id: Approval
  attributes:
    label: Approved / Pending
    description: Is the content Approved?
    placeholder: Approved
  validations:
    required: false
- type: input
  id: approver
  attributes:
    label: Approved by
    description: The content is approved by
    placeholder: ex. John Sample
  validations:
    required: false
- type: input
  id: From
  attributes:
    label: Email From
    description: Email from address?
    placeholder: ex. marketing@marketing.com
  validations:
    required: false
- type: input
  id: Reply
  attributes:
    label: Reply to
    description: Reply to address?
    placeholder: ex. marketing@marketing.com
  validations:
    required: false
- type: input
  id: test
  attributes:
    label: Test Email Recepients
    description: Who will receive the test email?
    placeholder: ex. marketing@marketing.com
  validations:
    required: false
- type: input
  id: sfid
  attributes:
    label: Salesforce Campaign ID
    description: Provide Salesforce Campaign ID
    placeholder: ex. 7013o000002SggXXXX
  validations:
    required: false
- type: input
  attributes:
    label: Email name
    description: Please add the email name followed by its send order.
    placeholder: Campaign_name-Invite-Email-1
- type: input
  attributes:
    label: Email pre-header
    description: Please add the pre-header for your email
    placeholder: You are invited to GitHub webinar
- type: input
  attributes:
    label: Email subject
    description: Add the email subject
    placeholder: GitHub webinar coming up
- type: textarea
  attributes:
    label: Email header image
    description: Add the header image
    placeholder: Drag and drop the image from your computer here
- type: textarea
  attributes:
    label: Email body
    description: Add the content of your email
    placeholder: Need help with Markdown email templates? Feel free to use one of these.

