---
name: Lead Upload Request
description: MOPS Lead Upload template
body:
- type: dropdown
    id: Region
    attributes:
      label: What region are these leads from?
      description: AMER, APAC, EMEA, or GLOBAL.
      options:
        - AMER
        - APAC
        - EMEA
        - GLOBAL
    validations:
      required: true
      
- type: input
  id: Master
  attributes:
    label: Master Issue Link
    description: Link to master Issue for this component
    placeholder: ex. https://github.com/github/marketing-operations/issues/3882
  validations:
    required: true
- type: input
  id: destination
  attributes:
    label: Lead Upload to Eloqua and/or SFDC
    description: Please indicate where the leads will be uploaded
    placeholder: Eloqua tab A and SFDC tab B
  validations:
    required: false
- type: input
  id: sfid
  attributes:
    label: Salesforce Campaign ID
    description: It can be found in the SFDC campaign URL after /Campaign/. 7013o000002CbkaAAC in the example below
    
                 https://github.lightning.force.com/lightning/r/Campaign/7013o000002CbkaAAC/view
    placeholder: ex. 7013o000002SggXXXX
  validations:
    required: false
- type: textarea
  attributes:
    label: Please link us to the Google Sheet file with the leads to be uploaded
    description: Please submit a Google Sheets document following this format
           https://docs.google.com/spreadsheets/d/1KWxXlpftZ4j9HFfpKgyQAhkGmqTS0UkmjyjACnnhddg/edit?usp=sharing
           
           If leads are preassigned, use this format
           https://docs.google.com/spreadsheets/d/1KWxXlpftZ4j9HFfpKgyQAhkGmqTS0UkmjyjACnnhddg/edit?usp=sharing
    placeholder: Lead file
  validations:
    required: true
