name: Nurture campaign support request - MOPs
description: Request support for a Nurture campaign
title: "Batch: [Nurture] - "
labels: ["Nurture"]
body:
  - type: markdown
    attributes:
      value: |
        ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)
        
        Hey there, I am the MOPs bot! In this repo we use ChatOps to streamline our communication and run development and operations functions. Because of that you will see me around a lot! Don't be a stranger :wink:
        
        Please go ahead and fill out the basic information needed for a Nurture below then hit `Submit new issue` and I'll be back with next steps.
        
        One last tip before I let you go. We will be using `/commands` to build the assets of this Nurture and I will tell you more about it after you hit `Submit`.
  - type: dropdown
    id: Region
    attributes:
      label: What region are you in?
      description: We have primary contacts assigned per region. Please let us know your region for assigment purposes.
      options:
        - I am based in AMER
        - I am based in APAC
        - I am based in EMEA
    validations:
      required: true
  - type: input
    id: test-approval
    attributes:
      label: Who should receive assets test for final approval
      description: Provide final assets approver's contact
      placeholder: brunochester@github.com
    validations:
      required: true    
  - type: input
    id: Name
    attributes:
      label: Nurture name
      description: What is the nurture name?
      placeholder: Email DevOps roundtable
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: More information about this nurture
      description: Feel free to link us to an IDM Master issue if you've one opened already.
      placeholder: Please do not add any asset information here.
    validations:
      required: true
  - type: input
    id: SFDC
    attributes:
      label: SalesForce Campaign Id
      description: What is the SalesForce Campaign Id?
      placeholder: 700033eedgrAAK
    validations:
      required: false
  - type: textarea
    id: Exit
    attributes:
      label: Nurture_exit_criteria
      description: Please let us know what the exit criteria are for this nurture
      placeholder: ex. user openned and clicked on an email asset or user submitted a contact us form
    validations:
      required: true
  - type: textarea
    id: frequency
    attributes:
      label: Email frequency
      description: Please let us know in what frequency you would like the emails to be sent
      placeholder: ex. start on xx/xx/xxxx and send following emails weekly
    validations:
      required: true
  - type: textarea
    id: audience
    attributes:
      label: Audience
      description: Please let us know the audience you are targeting
      placeholder: ex. Users who opted-in for an enterprise acount in EMEA during Q3/2021
    validations:
      required: true
  - type: dropdown
    id: evergreen
    attributes:
      label: Is it an evergreen nurture?
      description: Evergreen Nurtures can be used throughout the year by adding people to it as they meet the criteria set.
      options:
        - I want this campaign to be continuously sent to people as they meet the entrance criteria/audience
        - I want this campaign to be sent to the audience above just once
    validations:
      required: true
  - type: textarea
    attributes:
      label: Optional copy doc
      description: |
        - Provide a link to your copy doc if you have one, otherwise, the MOPs Bot will give you further instructions.
    validations: 
      required: false
 - type: fill
  template: "-[] {{ data.Nurture_exit_criteria }}"    
