name: System Access Request
description: Requesting access to a system that MOPs oversees
title: "Task: [System Access Request]"
labels: [system-access]
body: 
 - type: markdown
    attributes:
      value: |
        ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)
        
        Hey there, I am the MOPs bot! In this repo we use ChatOps to streamline our communication and run development and operations functions. Because of that you will see me around a lot! Don't be a stranger :wink:
        
        Pleas
        
 - type: input
   id: Handle
   attributes:
     label: GitHub Label
     description: What is your Github Handle?
     placeholder: "@myhandle"
   validations:
     required: true
      
  - type: input
    id: Manager_Handle
    attributes:
      label: Manager GitHub Label
      description: What is your Manager's GitHub Handle?
      placeholder: "@mymanagerhandle"
    validations:
      required: true    
      
  - type: textarea
    id: user-story
    attributes:
      label: Business REason
      placeholder: Tell us the use cases that justify your access
    validations:
      required: true
      
  - type: dropdown
    id: system-list
    attributes:
      label: Systems
      options:
        - Eloqua
        - SendGrid
        - MailChimp
        - Tray.io
        - Clearbit
