name: Campaign support request - MOPs
description: Request support for a campaign with 1+ emails and Landing pages
body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening a Campaign Support ticket.
  - type: input
    id: Name
    attributes:
      label: Campaign name
      description: What is the campaign name?
      placeholder: Email DevOps roundtable
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: More information about campaign
      description: Please add more information about the campaign. Feel free to link us to a IDM Master issue you've one opened already.
      render: shell
    validations:
      required: true

  - type: dropdown
    id: Region
    attributes:
      label: What region are you targeting?
      description: AMER, APAC, EMEA, or GLOBAL.
      options:
        - AMER
        - APAC
        - EMEA
        - GLOBAL
    validations:
      required: true

  - type: input
    id: SalesForce Campaign Id
    attributes:
      label: SalesForce Campaign Id
      description: What is the SalesForce Campaign Id?
      placeholder: 7013o000002SggWAAS
    validations:
      required: false
      
  - type: textarea
    id: Proposed Audience
    attributes:
      label: Proposed campaign audience
      description: What audience are you targeting for this campaign?
      placeholder: Attendees from the DevOps and Developer Experience week at GitHub InFocus located in the U.S
    validations:
      required: false
