name: Webinar Campaign support request
description: Request support for a Webinar campaign with 1+ emails and Landing pages
title: "Batch: [Webinar] - "
labels: [Webinar]
body:
  - type: markdown
    attributes:
      value: |
        ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)
        
        Hey there, I am the MOPs bot! In this repo we use ChatOps to streamline our communication and run development and operations functions. Because of that you will see me around a lot! Don't be a stranger :wink:
        
        Please go ahead and fill out the basic information needed for a Webinar campiagn below then hit `Submit new issue` and I'll be back with next steps.  
  - type: dropdown
    id: Region
    attributes:
      label: What region are you in?
      description: We have primary contacts assigned per region. Please let us know your region for assigment purposes.
      options:
        - I am based in AMER
        - I am based in APAC
        - I am based in EMEA
    validations:
      required: true
  - type: input
    id: Name
    attributes:
      label: Campaign name
      description: What is the campaign name?
      placeholder: Email DevOps roundtable
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: More information about campaign
      description: Please add more information about the campaign.
      placeholder: "Feel free to link us to a IDM Master issue you've one opened already."
    validations:
      required: true
  - type: input
    id: SFDC
    attributes:
      label: SalesForce Campaign Id
      description: What is the SalesForce Campaign Id?
      placeholder: 700033eedgrAAK
    validations:
      required: false
  - type: textarea
    id: Video
    attributes:
      label: Webinar technical infomation
      description: Please let us know the tool you will be using and the webinar specifications
      placeholder: ex. link to Zoom or Goldcast Event and Form id or GoToWebinar Registration url and webinar id
    validations:
      required: true
  - type: input
    id: test-approval
    attributes:
      label: Who should receive assets test for final approval
      description: Provide final assets approver's contact
      placeholder: brunochester@github.com
    validations:
      required: true
  - type: checkboxes
    id: task_list
    attributes:
      label: Webinar Task list - Skip this part until the MOPs Bot gives you further directions.
      description: Only possible values for YOUR-REGION are AMER, EMEA, or APAC <example> Task Webinar emails - AMER - DevSecOps Summer 2022
      options:
        - label: "**_Task: Webinar emails -_** YOUR-REGION - YOUR-CUSTOM-TITLE"
          required: false
        - label: "**_Task: Webinar landing pages -_** YOUR-REGION - YOUR-CUSTOM-TITLE"
          required: false
        - label: "**_Task: Webinar lead upload -_** YOUR-REGION - YOUR-CUSTOM-TITLE"
          required: false  
