name: Webinar Campaign support request - MOPs
description: Request support for a Webinar campaign with 1+ emails and Landing pages
body:
  - type: markdown
    attributes:
      value: |
        Thanks for opening a Campaign Support ticket.
  - type: input
    id: Name
    attributes:
      label: Campaign name
      description: What is the campaign name?
      placeholder: Email DevOps roundtable
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: More information about campaign
      description: Please add more information about the campaign. Feel free to link us to a IDM Master issue you've one opened already.
      render: shell
    validations:
      required: true

  - type: dropdown
    id: Region
    attributes:
      label: What region are you targeting?
      description: AMER, APAC, EMEA, or GLOBAL.
      options:
        - AMER
        - APAC
        - EMEA
        - GLOBAL
    validations:
      required: true

  - type: input
    id: SFDC
    attributes:
      label: SalesForce Campaign Id
      description: What is the SalesForce Campaign Id?
      placeholder: 7013o000002SggWAAS
    validations:
      required: false
      
  - type: textarea
    id: Audience
    attributes:
      label: Proposed campaign audience
      description: What audience are you targeting for this campaign?
      placeholder: Audience traits
    validations:
      required: false
           
  
  - type: input
    id: Webinartool
    attributes:
      label: What tool are you using to host your Webinar?
      description: Zoom or GoldCast or GoToWebinar
      placeholer: GoldCast
    validations:
      required: true

      
  - type: dropdown
    id: page
    attributes:
      label: How many landing pages are needed?
      description: Please select the number of landing pages needed for this campaign
      options:
        - One
        - Two
        - Three
        - Four
        - Five or more
    validations:
      required: true
