name: Auto Comment
on: [issues]
jobs:
 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: '[{"keywords": ["I am based in AMER"], "labels": ["AMER", "grey", "MOPS"], "assignees": ["BrunoChester"]}, {"keywords": ["I am based in EMEA"], "labels": ["EMEA", "grey", "MOPS"], "assignees": ["jason-araujo"]}, {"keywords": ["I am based in APAC"], "labels": ["APAC", "grey", "MOPS"], "assignees": ["jason-araujo"]}, {"keywords": ["Description of Enhancement Request"], "labels": ["grey", "MOPS"], "assignees": ["mike421453"]}, {"keywords": ["Task: [System Access Request]"], "labels": ["grey", "MOPS"], "assignees": ["mike421453"]}, {"keywords": ["Landing page"], "labels": ["landing-page", "grey", "MOPS"], "assignees": [""]}]'
          github-token: "${{ secrets.SECRET_NAME }}"

  nurture-comment:
    # needs: test
    if: github.event.label.name == 'Nurture'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)
            
            👋 @${{ github.event.issue.user.login }}! If you've given us the copy doc please disregard this message, otherwise, let's get you focused on asset creation!
            
            - [Here](#https://github.com/GitHub-MOPs/Test_repo/issues/165) is a collection of templates that might be helpful for you and speed-up your asset creation process.
            
            - Feeling ready? Please go ahead and type `/Email Builder` as a comment below to start :rocket:


  single-email-comment:
    # needs: test
    if: github.event.label.name == 'Single-Email'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)

            Hey there @${{ github.event.issue.user.login }}!

            Single Emails are straight forward and I believe we already have all that is needed to work on it for you.

            In case of any additional questions @${{ github.event.issue.assignee }} will get in touch.

            Thank you!

  Lead-Upload-comment:
    # needs: test
    if: github.event.label.name == 'Lead Upload'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)

            👋 @${{ github.event.issue.user.login }}!

            We will pick it up from here :smile:

            Thank you!

  Enhancement-Report-comment:
    # needs: test
    if: github.event.label.name == 'help-wanted'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)

            @${{ github.event.issue.user.login }}, we have all that is needed for initial triage and @${{ github.event.issue.assignee }} will get back to you soon.

            Thank you!

  Webinar:
    # needs: test
    if: github.event.label.name == 'Webinar'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)

            @${{ github.event.issue.user.login }}, If you've given us the copy doc please disregard this message, otherwise, let's get you focused on asset creation!
            
            - [Here](#https://github.com/GitHub-MOPs/Test_repo/issues/165) is a collection of templates that might be helpful for you and speed-up your asset creation process.
            
            - Feeling ready? Please go ahead and type `/Email Builder` as a comment below to start :rocket:

            - In case you want to build landing pages type `/Webinar landing page` or `/Webinar thank you page` :sparkles: 


  SEO-page-comment:
    # needs: test
    if: github.event.label.name == 'landing-page'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)

            @${{ github.event.issue.user.login }}, I've successfully labelled and assigned the issue.

            Next @${{ github.event.issue.assignee }}  will get in touch with next steps :rocket:

            Thank you!

  System-access-comment:
    # needs: test
    if: github.event.label.name == 'landing-page'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)

            @${{ github.event.issue.user.login }}, I've successfully labelled and assigned the issue.

            Next @${{ github.event.issue.assignee }}  will get in touch with next steps :rocket:

            Thank you!
