name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 job01:
   if: contains(github.event.comment.html_url, '/issues/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: [ubuntu-latest]
   steps:
     - name: say hello
       if: contains(github.event.comment.body, 'Webinar')   # check the comment if it contains the keywords
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpenedReactions: 'hooray'
          issuesOpenedComment: |
            ![](http://images.github.media/EloquaImages/clients/GitHubInc/%7B64693387-8abe-494c-8af0-7bde046a64d1%7D_hubot_512.png)
            
