on: issue_comment

jobs:

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ github.event.comment.body == 'I like pizza'}}
    runs-on: ubuntu-latest
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "monalisa, doctocat, hubot"
          labels: "weekly sync, docs-team"
          title: "Team sync"
          body: |
            ### Agenda
            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording
                    
            ### Discussion Points
            Add things to discuss below
            - [Work this week](https://github.com/orgs/github/projects/3)
