name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        if: github.event.comment.body == 'Lead Upload'
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          body: |
            Testing
