name: Like pizza

on:
  issue_comment:

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body, 'Lead Upload to Eloqua and/or SFDC'}}
    steps:
      - name: Like pizza
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment succeeded! ✅',
            }); 
